### ISSUE TITLE
Return 400 when a user does not have access to BE

### ISSUE THREAD

**Issue by manuel-miranda** [dotCMS/com.dotcms.dotsaml#8]
Current behavior: when and user with Front End access tries to access Back End(/dotAdmin, /admin, /c) instead of the private Front End page causes an infinite redirect loop between idP and dotCMS.

Expected behavior: when and user with Front End access tries to access Back End(/dotAdmin, /admin, /c) instead of the private Front End page gets a 400 response from dotCMS since it doesn't have access to the Back End portal.

dotCMS: 5.3.8.2

SAML plugin version: 
- com.dotcms.samlbundle-20.12.jar (098c8917d0a017ae8cc2c8f7cb9a3989)
- com.dotcms.samlbundle.fragment-20.12.jar (d2f902f0c40363e8c7811ea396403f79)

Zendesk issue: https://dotcms.zendesk.com/agent/tickets/103357

**Comment by swicken-dotcms** [comment]
Added this to https://github.com/dotCMS/core/issues/22533 where we are tracking SAML improvements
